# Generated by Django 5.0.2 on 2024-04-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['username'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='User',
        ),
    ]
