# Generated by Django 5.0.2 on 2024-05-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Module', '0005_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان'),
        ),
    ]
